### ISSUE TITLE
respect to ido-related user's config

### ISSUE THREAD

**Issue by danil** [danil/ido-occur#1]
@sshbio

> Then, his could be replaced by this:
> (when (fboundp 'ido-vertical-mode) (ido-vertical-mode 1))

could you please install and test the latest version?

> I usethis nstead of vetical mode, and this does works all the same:
> (setq ido-decorations '("\n-> " "" "\n   " "\n   ..." "[" "]" " [No match]" " [Matched]" " [Not readable]" " [Too big]" " [Confirm]"))

thanks for advice)

**Comment by ghost** [comment]
Yes, sure! thank you!

**Comment by danil** [comment]
@sshbio you are welcome)
